# Copyright 2022 LieberLieber Software GmbH 
# Author: Daniel Siegl
# Description: Build the MTIP.sln and the Setup after each commit.

name: Build MTIP.sln
on: [push]
env:
  VisualStudioPath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.exe
  DisableOutOfProcPath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild\
jobs:
  build:
    runs-on: [self-hosted, pcs]
    timeout-minutes: 15
    
    steps:
     - name: Checkout Code
       uses: actions/checkout@v1
     
     - name: Setup MSBuild Path
       uses: microsoft/setup-msbuild@v1.1

    # msbuild can't build the setups used.    
    # we use this build step to see if the c# side of things works fine
     - name: Build Solution
       run: msbuild .\MTIP\MTIP.csproj /p:Configuration=Release

    #prepare devenv to be able to build setups
     - name: Prepare Devenv to be able to build setups
       working-directory: ${{env.DisableOutOfProcPath}}
       run: .\DisableOutOfProcBuild.exe

    #wait 60 seconds as the devenv build is asyncronous
    #sadly this is not really stable and will fail on the agent currently
     - name: Build Setup with Devenv
       run: |
            $file = "out.log"
            &"${{env.VisualStudioPath}}" ".\MTIPInstaller\MTIPInstaller.vdproj" /Build "Release|Any CPU" /out $file
            Start-Sleep -Seconds 30
            if ([System.IO.File]::Exists($file))
            {
              echo "Seems to have worked"
              type $file
            }
            else 
            {
              echo "creating the setup on the agent failed"
            }

     - name: Publish Binary Artifact
       uses: actions/upload-artifact@v3
       with:
          name: mtip-sparx-installer
          path: .\MTIPInstaller\Release\*.msi
          retention-days: 30
       
     